---
title: "Sample Report"
author: 
- "David Keyes"
- "R for the Rest of Us"
date: "6/4/2020"
output: 
  word_document:
    reference_docx: my-reference-document.docx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      include = TRUE,
                      warning = FALSE,
                      message = FALSE)
```

```{r}
library(skimr)
library(tidyverse)
library(flextable)
```

```{r}
nhanes <- read_csv("data/nhanes.csv")
```



# Introduction

This report is the best report ever. Pretty much the **bees' knees**. Can't say that I've *ever* seen a better report.

## Reasons Why This Report is the Best

- It's amazing
- It's quite amazing
- It's seriously amazing
  + Sub-point
  + Sub-point #2

## Analysis

```{r}
nhanes %>% 
  group_by(gender, age_decade) %>%
  filter(gender == "female") %>% 
  summarize(mean_active_days = mean(phys_active_days,
                                    na.rm = TRUE)) %>% 
  drop_na(age_decade) %>% 
  arrange(desc(mean_active_days)) %>% 
  flextable() %>% 
  width(width = 2)
```

